project:
  type: website

website:
  title: "DESN9002"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - L1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



